# Generated by Django 4.1.1 on 2022-09-09 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(max_length=32)),
                ('fec_ini', models.DateField()),
                ('fec_ter', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Flujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=256)),
                ('fec_creacion', models.DateField()),
                ('fec_ini', models.DateField()),
                ('fec_ter', models.DateField()),
                ('estado', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=256)),
                ('prioridad', models.IntegerField()),
                ('categoria', models.CharField(max_length=32)),
                ('fec_creacion', models.DateField()),
                ('fec_ini', models.DateField()),
                ('fec_ter', models.DateField()),
                ('estado', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad_Interna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_unidad', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_full', models.CharField(max_length=70)),
                ('rut', models.CharField(max_length=12)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=256)),
                ('fec_nac', models.DateField()),
                ('genero', models.CharField(max_length=16)),
                ('Contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.contrato')),
                ('Rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.rol')),
                ('Unidad_Interna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.unidad_interna')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable_Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_usr', models.IntegerField()),
                ('fk_tarea', models.IntegerField()),
                ('Tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tarea')),
                ('Usuarios', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable_Flujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_usr', models.IntegerField()),
                ('fk_tarea', models.IntegerField()),
                ('Flujo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.flujo')),
                ('Usuarios', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.usuarios')),
            ],
        ),
    ]
